language: php

sudo: false

php:
  - hhvm
  - 5.6
  - 7


env:
  - COMPOSER_OPTS="--prefer-lowest"

before_install:


install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - echo ">$TRAVIS_PHP_VERSION<";
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit -c phpunit.hhvm.xml --testsuite=travis; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --testsuite=travis --coverage-text --coverage-clover=coverage.clover; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

